# Generated by Django 4.1.3 on 2022-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1Hp', models.IntegerField(default=100)),
                ('player2Hp', models.IntegerField(default=100)),
            ],
        ),
    ]
